project_name: walletshield

release:
  draft: true
  github:
    owner: ZeroKnowledgeNetwork
    name: releaser
  name_template: "{{ .Tag }}"

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=1

# https://goreleaser.com/customization/verifiable_builds/
# gomod:
#   proxy: true
#   mod: mod
#   env:
#     - GOPROXY=https://proxy.golang.org,direct
#     - GOSUMDB=sum.golang.org
#     # - GOPRIVATE=example.com/blah

builds:
  - id: linux-amd64
    binary: walletshield
    main: ./apps/walletshield
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.GitCommit={{ .ShortCommit }}
      - -X main.GitTag={{ .Tag }}
      - -X main.BuildDate={{ .Timestamp }}

  - id: linux-arm64
    binary: walletshield
    main: ./apps/walletshield
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.GitCommit={{ .ShortCommit }}
      - -X main.GitTag={{ .Tag }}
      - -X main.BuildDate={{ .Timestamp }}

  # - id: linux-armhf
  #   binary: walletshield
  #   main: ./apps/walletshield
  #   goarch:
  #     - arm
  #   goarm:
  #     - 7
  #   goos:
  #     - linux
  #   env:
  #     - CC=arm-linux-gnueabihf-gcc
  #     - CXX=arm-linux-gnueabihf-g++
  #   flags:
  #     - -trimpath
  #   ldflags:
  #     - -s -w
  #     - -X main.version={{.Version}}
  #     - -X main.GitCommit={{ .ShortCommit }}
  #     - -X main.GitTag={{ .Tag }}
  #     - -X main.BuildDate={{ .Timestamp }}

  - id: darwin-amd64
    binary: walletshield
    main: ./apps/walletshield
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -trimpath

  - id: darwin-arm64
    binary: walletshield
    main: ./apps/walletshield
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -trimpath
    ldflags:
      - -v # verbose is useful

  - id: windows-amd64
    binary: walletshield
    main: ./apps/walletshield
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - CGO_LDFLAGS="-Wl,--allow-multiple-definition"
    flags:
      - -trimpath
      - -buildmode=exe

# - id: windows-386
#   binary: walletshield
#   main: ./apps/walletshield
#   goarch:
#     - 386
#   goos:
#     - windows
#   env:
#     - CC=/llvm-mingw/bin/i686-w64-mingw32-gcc
#     - CXX=/llvm-mingw/bin/i686-w64-mingw32-g++
#   flags:
#     - -trimpath
#     - -buildmode=exe

# - id: windows-arm64
#   binary: walletshield
#   main: ./apps/walletshield
#   goarch:
#     - arm64
#   goos:
#     - windows
#   env:
#     - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
#     - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
#   flags:
#     - -trimpath
#     - -buildmode=exe

upx:
  - enabled: true
    goos: [linux, darwin, windows]
    goarch: [arm64, amd64]
    compress: best
    lzma: true
    brute: true

universal_binaries:
  - id: darwin-universal
    ids:
      - darwin-amd64
      - darwin-arm64
    replace: true
    name_template: walletshield

archives:
  - id: release/version
    builds:
      - linux-amd64
      - linux-arm64
      - darwin-universal
      - windows-amd64
      # - linux-armhf
      # - windows-386
      # - windows-arm64
    name_template: >-
      {{ .ProjectName }}-
      {{- .Tag }}-
      {{- if eq .Os "darwin" }}MacOS
      {{- else }}{{- title .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: false
    format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Tag }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
